apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
spec:
  storageClassName: mysqldatabase
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi