apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-database-persistence
  labels:
    type: local
spec:
  storageClassName: mysqldatabase
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/microservice/database"