apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  username: dXNlck9mREIK
  password: VXNlcjAxCg==

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root: cm9vdAo=
  username: Y2hhdFVzZXIK 
  password: dXNlcm9mQ2hhdAo=